//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Write_file", ReplyAction="http://tempuri.org/IService/Write_fileResponse")]
        void Write_file(string path, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Write_file", ReplyAction="http://tempuri.org/IService/Write_fileResponse")]
        System.Threading.Tasks.Task Write_fileAsync(string path, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/get_content", ReplyAction="http://tempuri.org/IService/get_contentResponse")]
        string get_content(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/get_content", ReplyAction="http://tempuri.org/IService/get_contentResponse")]
        System.Threading.Tasks.Task<string> get_contentAsync(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/get_path", ReplyAction="http://tempuri.org/IService/get_pathResponse")]
        string get_path(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/get_path", ReplyAction="http://tempuri.org/IService/get_pathResponse")]
        System.Threading.Tasks.Task<string> get_pathAsync(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Read_file", ReplyAction="http://tempuri.org/IService/Read_fileResponse")]
        string Read_file(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Read_file", ReplyAction="http://tempuri.org/IService/Read_fileResponse")]
        System.Threading.Tasks.Task<string> Read_fileAsync(string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.Service.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.Service.IService>, Client.Service.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Write_file(string path, string content) {
            base.Channel.Write_file(path, content);
        }
        
        public System.Threading.Tasks.Task Write_fileAsync(string path, string content) {
            return base.Channel.Write_fileAsync(path, content);
        }
        
        public string get_content(string msg) {
            return base.Channel.get_content(msg);
        }
        
        public System.Threading.Tasks.Task<string> get_contentAsync(string msg) {
            return base.Channel.get_contentAsync(msg);
        }
        
        public string get_path(string path) {
            return base.Channel.get_path(path);
        }
        
        public System.Threading.Tasks.Task<string> get_pathAsync(string path) {
            return base.Channel.get_pathAsync(path);
        }
        
        public string Read_file(string path) {
            return base.Channel.Read_file(path);
        }
        
        public System.Threading.Tasks.Task<string> Read_fileAsync(string path) {
            return base.Channel.Read_fileAsync(path);
        }
    }
}
