//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/intput_x", ReplyAction="http://tempuri.org/IService1/intput_xResponse")]
        int intput_x(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/intput_x", ReplyAction="http://tempuri.org/IService1/intput_xResponse")]
        System.Threading.Tasks.Task<int> intput_xAsync(int x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/input_y", ReplyAction="http://tempuri.org/IService1/input_yResponse")]
        int input_y(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/input_y", ReplyAction="http://tempuri.org/IService1/input_yResponse")]
        System.Threading.Tasks.Task<int> input_yAsync(int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/operation", ReplyAction="http://tempuri.org/IService1/operationResponse")]
        int operation(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/operation", ReplyAction="http://tempuri.org/IService1/operationResponse")]
        System.Threading.Tasks.Task<int> operationAsync(int x, int y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.Service.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.Service.IService1>, Client.Service.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int intput_x(int x) {
            return base.Channel.intput_x(x);
        }
        
        public System.Threading.Tasks.Task<int> intput_xAsync(int x) {
            return base.Channel.intput_xAsync(x);
        }
        
        public int input_y(int y) {
            return base.Channel.input_y(y);
        }
        
        public System.Threading.Tasks.Task<int> input_yAsync(int y) {
            return base.Channel.input_yAsync(y);
        }
        
        public int operation(int x, int y) {
            return base.Channel.operation(x, y);
        }
        
        public System.Threading.Tasks.Task<int> operationAsync(int x, int y) {
            return base.Channel.operationAsync(x, y);
        }
    }
}
